export const COMPONENTID = "componentId";
export const MAKE = "make";
export const MODEL = "model";
export const PRICE = "price";
export const IMAGE = "image";
export const HEIGHT = "height";
export const COOLINGTYPE = "coolingType";
export const RADIATORLENGTH = "radiatorLength";
export const NUMBEROFHEATPIPES = "numberOfHeatPipes";

export const COMPONENTID_LABEL = "Component ID";
export const MAKE_LABEL = "Make";
export const MODEL_LABEL = "Model";
export const PRICE_LABEL = "Price";
export const IMAGE_LABEL = "Image";
export const HEIGHT_LABEL = "Cooler height";
export const COOLINGTYPE_LABEL = "Cooling type";
export const RADIATORLENGTH_LABEL = "Radiator length";
export const NUMBEROFHEATPIPES_LABEL = "Number of heat pipes";
